version: '3.8'

services: 
    postgre:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: asdasd
        ports:
            - '5432:5432'
        volumes: 
            - ./dbdata:/var/lib/postgresql/data
        networks:
            - minha-rede
    backend:
        image: node
        restart: always
        image: "node:12.14.0"
        volumes:
            - "./nodedata/:/nodejs"
        working_dir: /nodejs
        entrypoint: "npm start"
        environment:
            TZ: America/Sao_Paulo
        networks:
            - minha-rede
    frontend:
        image: node
        restart: always
        image: "node:12.14.0"
        volumes:
            - "./frontenddata/:/nodejs"
        working_dir: /nodejs
        entrypoint: "npm start"
        environment:
            TZ: America/Sao_Paulo
        networks:
            - minha-rede
networks:
    minha-rede:
        driver: bridge